=== ainhoavegasanchez/DigitalChef/back/manduca/Servicios/Xsd/Usuario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Usuario">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Nick"/>
        <xs:element ref="Pass"/>
        <xs:element ref="Datas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Nick" type="xs:NCName"/>
  <xs:element name="Pass" type="xs:NCName"/>
  <xs:element name="Datas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="SurName"/>
        <xs:element ref="FullAddress"/>
        <xs:element ref="Phone"/>
        <xs:element minOccurs="0" ref="Email"/>
        <xs:element ref="Latitude"/>
        <xs:element ref="Longitude"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Name" type="xs:NCName"/>
  <xs:element name="SurName" type="xs:NCName"/>
  <xs:element name="FullAddress" type="xs:string"/>
  <xs:element name="Phone" type="xs:integer"/>
  <xs:element name="Email" type="xs:string"/>
  <xs:element name="Latitude" type="xs:decimal"/>
  <xs:element name="Longitude" type="xs:decimal"/>
</xs:schema>

=== ainhoavegasanchez/DigitalChef/back/manduca/Test/Fijos/Usuario/Francisco.xml
<?xml version="1.0" encoding="UTF-8"?>
<Usuario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../Servicios/Xsd/Usuario.xsd">
    <Nick>francisco</Nick>
    <Pass>profPort</Pass>
    <Datas>
        <Name>Francisco</Name>
        <SurName>Cabrera</SurName>
        <FullAddress>c/Competa s/n, 29006 Málaga</FullAddress>
        <Phone>655472596</Phone>
        <Latitude>36.719313253453656</Latitude>
        <Longitude>36.719313253453656</Longitude>
    </Datas>
</Usuario>

=== ainhoavegasanchez/DigitalChef/back/manduca/Test/Fijos/Usuario/Rafa.xml
<?xml version="1.0" encoding="UTF-8"?>
<Usuario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../../Servicios/Xsd/Usuario.xsd">
    <Nick>rafa</Nick>
    <Pass>alumRaf</Pass>
    <Datas>
        <Name>Rafael</Name>
        <SurName>Bonilla</SurName>
        <FullAddress>c/Medina Azahara 45 Arroyo de la Miel, 29631</FullAddress>
        <Phone>65524877</Phone>
        <Email>rafabonilla@gmail.com</Email>
        <Latitude>36.602621769643726</Latitude>
        <Longitude>-4.528972348808231</Longitude>
    </Datas>
</Usuario>
